apiVersion: v1
kind: Service
metadata:
  name: nodejs-server
  namespace: default
spec:
  ports:
  - port: 8001
    protocol: TCP
    targetPort: 8001
  selector:
    app: nodejs-server
  type: NodePort
