apiVersion: apps/v1
kind: Deployment
metadata:
  name: python-server
  namespace: default
spec:
  selector:
    matchLabels:
      app: python-server
  replicas: 1
  template:
    metadata:
      labels:
        app: python-server
    spec:
      containers:
      - name: python-server
        image: shovan1995/python-server:1.0
        ports:
        - containerPort: 8002
