apiVersion: v1
kind: Service
metadata:
  name: python-server
  namespace: default
spec:
  ports:
  - port: 8002
    protocol: TCP
    targetPort: 8002
  selector:
    app: python-server
  type: NodePort
